//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRelojLaboral.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RelojLaboralEntities : DbContext
    {
        public RelojLaboralEntities()
            : base("name=RelojLaboralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RL_Asistencia> RL_Asistencia { get; set; }
        public virtual DbSet<RL_CalendarioEstado> RL_CalendarioEstado { get; set; }
        public virtual DbSet<RL_CalendarioPersonal> RL_CalendarioPersonal { get; set; }
        public virtual DbSet<RL_Dia> RL_Dia { get; set; }
        public virtual DbSet<RL_Geolocalizacion> RL_Geolocalizacion { get; set; }
        public virtual DbSet<RL_HorarioPersonal> RL_HorarioPersonal { get; set; }
        public virtual DbSet<RL_HorarioTipo> RL_HorarioTipo { get; set; }
        public virtual DbSet<RL_Notificaciones> RL_Notificaciones { get; set; }
        public virtual DbSet<RL_Permisos> RL_Permisos { get; set; }
        public virtual DbSet<RL_PreferenciaPersonal> RL_PreferenciaPersonal { get; set; }
        public virtual DbSet<RL_Preferencias> RL_Preferencias { get; set; }
        public virtual DbSet<RL_Roles> RL_Roles { get; set; }
        public virtual DbSet<RL_Ubigeo> RL_Ubigeo { get; set; }
        public virtual DbSet<RL_Usuario> RL_Usuario { get; set; }
        public virtual DbSet<RL_UsuarioEstado> RL_UsuarioEstado { get; set; }
        public virtual DbSet<RL_UsuarioGrupo> RL_UsuarioGrupo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual int SelectCalendarioIndividual()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectCalendarioIndividual");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_del_RL_HorarioPersonal(Nullable<int> nHoPId)
        {
            var nHoPIdParameter = nHoPId.HasValue ?
                new ObjectParameter("nHoPId", nHoPId) :
                new ObjectParameter("nHoPId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_del_RL_HorarioPersonal", nHoPIdParameter);
        }
    
        public virtual int sp_del_RL_Usuario(Nullable<int> nUsuId)
        {
            var nUsuIdParameter = nUsuId.HasValue ?
                new ObjectParameter("nUsuId", nUsuId) :
                new ObjectParameter("nUsuId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_del_RL_Usuario", nUsuIdParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_get_RL_Dia_Result> sp_get_RL_Dia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_RL_Dia_Result>("sp_get_RL_Dia");
        }
    
        public virtual ObjectResult<sp_get_RL_HorarioTipo_Result> sp_get_RL_HorarioTipo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_RL_HorarioTipo_Result>("sp_get_RL_HorarioTipo");
        }
    
        public virtual ObjectResult<sp_get_RL_Roles_Result> sp_get_RL_Roles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_RL_Roles_Result>("sp_get_RL_Roles");
        }
    
        public virtual ObjectResult<sp_get_RL_Ubigeo_Result> sp_get_RL_Ubigeo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_RL_Ubigeo_Result>("sp_get_RL_Ubigeo");
        }
    
        public virtual ObjectResult<sp_get_RL_Usuario_Result> sp_get_RL_Usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_RL_Usuario_Result>("sp_get_RL_Usuario");
        }
    
        public virtual ObjectResult<sp_get_RL_UsuarioEstado_Result> sp_get_RL_UsuarioEstado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_RL_UsuarioEstado_Result>("sp_get_RL_UsuarioEstado");
        }
    
        public virtual ObjectResult<sp_getDNI_RL_Usuario_Result> sp_getDNI_RL_Usuario(string cUsuDNI)
        {
            var cUsuDNIParameter = cUsuDNI != null ?
                new ObjectParameter("cUsuDNI", cUsuDNI) :
                new ObjectParameter("cUsuDNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getDNI_RL_Usuario_Result>("sp_getDNI_RL_Usuario", cUsuDNIParameter);
        }
    
        public virtual ObjectResult<sp_getId_RL_Horario_Result> sp_getId_RL_Horario(Nullable<int> nUsuId)
        {
            var nUsuIdParameter = nUsuId.HasValue ?
                new ObjectParameter("nUsuId", nUsuId) :
                new ObjectParameter("nUsuId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getId_RL_Horario_Result>("sp_getId_RL_Horario", nUsuIdParameter);
        }
    
        public virtual ObjectResult<sp_getId_RL_Usuario_Result> sp_getId_RL_Usuario(Nullable<int> nUsuId)
        {
            var nUsuIdParameter = nUsuId.HasValue ?
                new ObjectParameter("nUsuId", nUsuId) :
                new ObjectParameter("nUsuId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getId_RL_Usuario_Result>("sp_getId_RL_Usuario", nUsuIdParameter);
        }
    
        public virtual ObjectResult<sp_getValida_RL_Usuario_Result> sp_getValida_RL_Usuario(string cUsuEmail, string cUsuPassword)
        {
            var cUsuEmailParameter = cUsuEmail != null ?
                new ObjectParameter("cUsuEmail", cUsuEmail) :
                new ObjectParameter("cUsuEmail", typeof(string));
    
            var cUsuPasswordParameter = cUsuPassword != null ?
                new ObjectParameter("cUsuPassword", cUsuPassword) :
                new ObjectParameter("cUsuPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getValida_RL_Usuario_Result>("sp_getValida_RL_Usuario", cUsuEmailParameter, cUsuPasswordParameter);
        }
    
        public virtual ObjectResult<sp_getX_RL_Usuario_Result> sp_getX_RL_Usuario(string cUsuNombre, string cUsuDNI, string cUsuApellido)
        {
            var cUsuNombreParameter = cUsuNombre != null ?
                new ObjectParameter("cUsuNombre", cUsuNombre) :
                new ObjectParameter("cUsuNombre", typeof(string));
    
            var cUsuDNIParameter = cUsuDNI != null ?
                new ObjectParameter("cUsuDNI", cUsuDNI) :
                new ObjectParameter("cUsuDNI", typeof(string));
    
            var cUsuApellidoParameter = cUsuApellido != null ?
                new ObjectParameter("cUsuApellido", cUsuApellido) :
                new ObjectParameter("cUsuApellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getX_RL_Usuario_Result>("sp_getX_RL_Usuario", cUsuNombreParameter, cUsuDNIParameter, cUsuApellidoParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_ins_RL_Asistencia(Nullable<int> nUsuId, string cAsiIp, string cAsiHoraInicio, string cAsiHoraFinal, string cAsiDispositivo, string cAsiFecha)
        {
            var nUsuIdParameter = nUsuId.HasValue ?
                new ObjectParameter("nUsuId", nUsuId) :
                new ObjectParameter("nUsuId", typeof(int));
    
            var cAsiIpParameter = cAsiIp != null ?
                new ObjectParameter("cAsiIp", cAsiIp) :
                new ObjectParameter("cAsiIp", typeof(string));
    
            var cAsiHoraInicioParameter = cAsiHoraInicio != null ?
                new ObjectParameter("cAsiHoraInicio", cAsiHoraInicio) :
                new ObjectParameter("cAsiHoraInicio", typeof(string));
    
            var cAsiHoraFinalParameter = cAsiHoraFinal != null ?
                new ObjectParameter("cAsiHoraFinal", cAsiHoraFinal) :
                new ObjectParameter("cAsiHoraFinal", typeof(string));
    
            var cAsiDispositivoParameter = cAsiDispositivo != null ?
                new ObjectParameter("cAsiDispositivo", cAsiDispositivo) :
                new ObjectParameter("cAsiDispositivo", typeof(string));
    
            var cAsiFechaParameter = cAsiFecha != null ?
                new ObjectParameter("cAsiFecha", cAsiFecha) :
                new ObjectParameter("cAsiFecha", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_RL_Asistencia", nUsuIdParameter, cAsiIpParameter, cAsiHoraInicioParameter, cAsiHoraFinalParameter, cAsiDispositivoParameter, cAsiFechaParameter);
        }
    
        public virtual int sp_ins_RL_HorarioPersonal(Nullable<int> nHoTId, Nullable<int> nDiaId, Nullable<int> nUsuId, string cHoPInicio, string cHoPFinal, string cHoPZonaHoraria)
        {
            var nHoTIdParameter = nHoTId.HasValue ?
                new ObjectParameter("nHoTId", nHoTId) :
                new ObjectParameter("nHoTId", typeof(int));
    
            var nDiaIdParameter = nDiaId.HasValue ?
                new ObjectParameter("nDiaId", nDiaId) :
                new ObjectParameter("nDiaId", typeof(int));
    
            var nUsuIdParameter = nUsuId.HasValue ?
                new ObjectParameter("nUsuId", nUsuId) :
                new ObjectParameter("nUsuId", typeof(int));
    
            var cHoPInicioParameter = cHoPInicio != null ?
                new ObjectParameter("cHoPInicio", cHoPInicio) :
                new ObjectParameter("cHoPInicio", typeof(string));
    
            var cHoPFinalParameter = cHoPFinal != null ?
                new ObjectParameter("cHoPFinal", cHoPFinal) :
                new ObjectParameter("cHoPFinal", typeof(string));
    
            var cHoPZonaHorariaParameter = cHoPZonaHoraria != null ?
                new ObjectParameter("cHoPZonaHoraria", cHoPZonaHoraria) :
                new ObjectParameter("cHoPZonaHoraria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_RL_HorarioPersonal", nHoTIdParameter, nDiaIdParameter, nUsuIdParameter, cHoPInicioParameter, cHoPFinalParameter, cHoPZonaHorariaParameter);
        }
    
        public virtual int sp_ins_RL_Usuario(Nullable<int> nUbiId, string cUsuNombre, string cUsuApellido, string cUsuDNI, string cUsuCelular1, string cUsuCelular2, string cUsuEmail, string cUsuDomicilio)
        {
            var nUbiIdParameter = nUbiId.HasValue ?
                new ObjectParameter("nUbiId", nUbiId) :
                new ObjectParameter("nUbiId", typeof(int));
    
            var cUsuNombreParameter = cUsuNombre != null ?
                new ObjectParameter("cUsuNombre", cUsuNombre) :
                new ObjectParameter("cUsuNombre", typeof(string));
    
            var cUsuApellidoParameter = cUsuApellido != null ?
                new ObjectParameter("cUsuApellido", cUsuApellido) :
                new ObjectParameter("cUsuApellido", typeof(string));
    
            var cUsuDNIParameter = cUsuDNI != null ?
                new ObjectParameter("cUsuDNI", cUsuDNI) :
                new ObjectParameter("cUsuDNI", typeof(string));
    
            var cUsuCelular1Parameter = cUsuCelular1 != null ?
                new ObjectParameter("cUsuCelular1", cUsuCelular1) :
                new ObjectParameter("cUsuCelular1", typeof(string));
    
            var cUsuCelular2Parameter = cUsuCelular2 != null ?
                new ObjectParameter("cUsuCelular2", cUsuCelular2) :
                new ObjectParameter("cUsuCelular2", typeof(string));
    
            var cUsuEmailParameter = cUsuEmail != null ?
                new ObjectParameter("cUsuEmail", cUsuEmail) :
                new ObjectParameter("cUsuEmail", typeof(string));
    
            var cUsuDomicilioParameter = cUsuDomicilio != null ?
                new ObjectParameter("cUsuDomicilio", cUsuDomicilio) :
                new ObjectParameter("cUsuDomicilio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_RL_Usuario", nUbiIdParameter, cUsuNombreParameter, cUsuApellidoParameter, cUsuDNIParameter, cUsuCelular1Parameter, cUsuCelular2Parameter, cUsuEmailParameter, cUsuDomicilioParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upd_RL_Usuario(Nullable<int> nUsuId, Nullable<int> nUbiId, string cUsuNombre, string cUsuApellido, string cUsuDNI, string cUsuCelular1, string cUsuCelular2, string cUsuEmail, string cUsuDomicilio, string cUsuPassword, Nullable<int> nUsEId)
        {
            var nUsuIdParameter = nUsuId.HasValue ?
                new ObjectParameter("nUsuId", nUsuId) :
                new ObjectParameter("nUsuId", typeof(int));
    
            var nUbiIdParameter = nUbiId.HasValue ?
                new ObjectParameter("nUbiId", nUbiId) :
                new ObjectParameter("nUbiId", typeof(int));
    
            var cUsuNombreParameter = cUsuNombre != null ?
                new ObjectParameter("cUsuNombre", cUsuNombre) :
                new ObjectParameter("cUsuNombre", typeof(string));
    
            var cUsuApellidoParameter = cUsuApellido != null ?
                new ObjectParameter("cUsuApellido", cUsuApellido) :
                new ObjectParameter("cUsuApellido", typeof(string));
    
            var cUsuDNIParameter = cUsuDNI != null ?
                new ObjectParameter("cUsuDNI", cUsuDNI) :
                new ObjectParameter("cUsuDNI", typeof(string));
    
            var cUsuCelular1Parameter = cUsuCelular1 != null ?
                new ObjectParameter("cUsuCelular1", cUsuCelular1) :
                new ObjectParameter("cUsuCelular1", typeof(string));
    
            var cUsuCelular2Parameter = cUsuCelular2 != null ?
                new ObjectParameter("cUsuCelular2", cUsuCelular2) :
                new ObjectParameter("cUsuCelular2", typeof(string));
    
            var cUsuEmailParameter = cUsuEmail != null ?
                new ObjectParameter("cUsuEmail", cUsuEmail) :
                new ObjectParameter("cUsuEmail", typeof(string));
    
            var cUsuDomicilioParameter = cUsuDomicilio != null ?
                new ObjectParameter("cUsuDomicilio", cUsuDomicilio) :
                new ObjectParameter("cUsuDomicilio", typeof(string));
    
            var cUsuPasswordParameter = cUsuPassword != null ?
                new ObjectParameter("cUsuPassword", cUsuPassword) :
                new ObjectParameter("cUsuPassword", typeof(string));
    
            var nUsEIdParameter = nUsEId.HasValue ?
                new ObjectParameter("nUsEId", nUsEId) :
                new ObjectParameter("nUsEId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upd_RL_Usuario", nUsuIdParameter, nUbiIdParameter, cUsuNombreParameter, cUsuApellidoParameter, cUsuDNIParameter, cUsuCelular1Parameter, cUsuCelular2Parameter, cUsuEmailParameter, cUsuDomicilioParameter, cUsuPasswordParameter, nUsEIdParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
