//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRelojLaboral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RL_CalendarioPersonal
    {
        public int nCaIId { get; set; }
        public Nullable<int> nDiaId { get; set; }
        public Nullable<int> nUsuId { get; set; }
        public Nullable<int> nEsCId { get; set; }
    
        public virtual RL_CalendarioEstado RL_CalendarioEstado { get; set; }
        public virtual RL_Dia RL_Dia { get; set; }
        public virtual RL_Usuario RL_Usuario { get; set; }
    }
}
