//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRelojLaboral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RL_Dia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RL_Dia()
        {
            this.RL_CalendarioPersonal = new HashSet<RL_CalendarioPersonal>();
            this.RL_HorarioPersonal = new HashSet<RL_HorarioPersonal>();
        }
    
        public int nDiaId { get; set; }
        public string cDiaNombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RL_CalendarioPersonal> RL_CalendarioPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RL_HorarioPersonal> RL_HorarioPersonal { get; set; }
    }
}
