//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRelojLaboral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RL_PreferenciaPersonal
    {
        public int nPInId { get; set; }
        public int nPreId { get; set; }
        public int nUsuId { get; set; }
        public int nPerId { get; set; }
        public int nNotId { get; set; }
        public int nGeoId { get; set; }
    
        public virtual RL_Geolocalizacion RL_Geolocalizacion { get; set; }
        public virtual RL_Notificaciones RL_Notificaciones { get; set; }
        public virtual RL_Permisos RL_Permisos { get; set; }
        public virtual RL_Preferencias RL_Preferencias { get; set; }
        public virtual RL_Usuario RL_Usuario { get; set; }
    }
}
