//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRelojLaboral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RL_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RL_Usuario()
        {
            this.RL_Asistencia = new HashSet<RL_Asistencia>();
            this.RL_CalendarioPersonal = new HashSet<RL_CalendarioPersonal>();
            this.RL_HorarioPersonal = new HashSet<RL_HorarioPersonal>();
            this.RL_PreferenciaPersonal = new HashSet<RL_PreferenciaPersonal>();
            this.RL_UsuarioGrupo = new HashSet<RL_UsuarioGrupo>();
        }
    
        public int nUsuId { get; set; }
        public Nullable<int> nUbiId { get; set; }
        public Nullable<int> nRolId { get; set; }
        public string cUsuNombre { get; set; }
        public string cUsuApellido { get; set; }
        public string cUsuDNI { get; set; }
        public string cUsuCelular1 { get; set; }
        public string cUsuCelular2 { get; set; }
        public string cUsuEmail { get; set; }
        public string cUsuDomicilio { get; set; }
        public string cUsuPassword { get; set; }
        public Nullable<int> nUsEId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RL_Asistencia> RL_Asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RL_CalendarioPersonal> RL_CalendarioPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RL_HorarioPersonal> RL_HorarioPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RL_PreferenciaPersonal> RL_PreferenciaPersonal { get; set; }
        public virtual RL_Roles RL_Roles { get; set; }
        public virtual RL_Ubigeo RL_Ubigeo { get; set; }
        public virtual RL_UsuarioEstado RL_UsuarioEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RL_UsuarioGrupo> RL_UsuarioGrupo { get; set; }
    }
}
